import { WorkspaceDTO } from '@/types';
import { AccountDTO } from '@/features/accounts/types/accounts';
import { TransactionDTO } from '@/features/transactions/types/transactions';
import { BudgetDTO } from '@/features/budgets/types/budgets';
import { SavingsGoalDTO } from '@/features/goals/types/goals';
import { SubscriptionDTO, SalaryDistributionConfig } from '@/features/subscriptions/types/subscriptions';
import { InvestmentDTO } from '@/features/investments/types/investments';
import { DebtBalanceSummaryDTO } from '@/features/settlements/types/settlements';
import { DashboardSummaryDTO } from '@/features/dashboard/types/dashboard';

export const DEMO_WORKSPACE_ID = 'demo-workspace-0000-0000-0000-000000000001';
export const DEMO_COUPLE_WORKSPACE_ID = 'demo-workspace-0000-0000-0000-000000000002';

export const DEMO_WORKSPACES: WorkspaceDTO[] = [
  {
    id: DEMO_WORKSPACE_ID,
    name: 'Espacio Personal (Demo)',
    description: 'Espacio de demostración de finanzas personales',
    type: 'INDIVIDUAL',
    currency: 'PEN',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: DEMO_COUPLE_WORKSPACE_ID,
    name: 'Hogar & Pareja (Demo)',
    description: 'Espacio compartido de demostración con Sofía',
    type: 'COUPLE',
    currency: 'PEN',
    createdAt: '2026-01-01T00:00:00Z',
    members: [
      {
        id: 'member-1',
        userId: 'demo-user-1',
        userName: 'Usuario Demo',
        userEmail: 'demo@dualis.app',
        role: 'OWNER',
        joinedAt: '2026-01-01T00:00:00Z',
      },
      {
        id: 'member-2',
        userId: 'demo-user-2',
        userName: 'Sofía',
        userEmail: 'sofia@demo.app',
        role: 'MEMBER',
        joinedAt: '2026-01-01T00:00:00Z',
      },
    ],
  },
];

export const DEMO_ACCOUNTS: AccountDTO[] = [
  {
    id: 'demo-acc-1',
    name: 'BCP Sueldo / Principal',
    type: 'BANK',
    balance: 4850.0,
    currency: 'PEN',
    accountNumber: '**** 4921',
    color: '#6366f1',
    workspaceId: DEMO_WORKSPACE_ID,
  },
  {
    id: 'demo-acc-2',
    name: 'Interbank Ahorro Emergencia',
    type: 'SAVINGS',
    balance: 8200.0,
    currency: 'PEN',
    accountNumber: '**** 1083',
    color: '#10b981',
    workspaceId: DEMO_WORKSPACE_ID,
  },
  {
    id: 'demo-acc-3',
    name: 'Billetera Yape / Efectivo',
    type: 'DIGITAL',
    balance: 380.0,
    currency: 'PEN',
    accountNumber: 'Yape 987***123',
    color: '#8b5cf6',
    workspaceId: DEMO_WORKSPACE_ID,
  },
  {
    id: 'demo-acc-4',
    name: 'Tarjeta Visa Signature',
    type: 'CREDIT_CARD',
    balance: -1250.0,
    currency: 'PEN',
    accountNumber: '**** 8842',
    color: '#f43f5e',
    workspaceId: DEMO_WORKSPACE_ID,
  },
];

export const DEMO_TRANSACTIONS: TransactionDTO[] = [
  {
    id: 'demo-tx-1',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-1',
    accountName: 'BCP Sueldo / Principal',
    categoryName: 'Alimentación',
    categoryIcon: 'ShoppingBag',
    categoryColor: '#10b981',
    amount: 145.5,
    currency: 'PEN',
    type: 'EXPENSE',
    description: 'Supermercado Wong - Compras quincena',
    transactionDate: new Date().toISOString(),
    paidByUserName: 'Tú',
  },
  {
    id: 'demo-tx-2',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-1',
    accountName: 'BCP Sueldo / Principal',
    categoryName: 'Salario / Ingresos',
    categoryIcon: 'Wallet',
    categoryColor: '#6366f1',
    amount: 6500.0,
    currency: 'PEN',
    type: 'INCOME',
    description: 'Abono de Nómina Empresa Tech',
    transactionDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    paidByUserName: 'Tú',
  },
  {
    id: 'demo-tx-3',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-1',
    accountName: 'BCP Sueldo / Principal',
    categoryName: 'Servicios',
    categoryIcon: 'Zap',
    categoryColor: '#f59e0b',
    amount: 189.0,
    currency: 'PEN',
    type: 'EXPENSE',
    description: 'Internet Fibra Óptica + Luz del Sur',
    transactionDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    paidByUserName: 'Tú',
  },
  {
    id: 'demo-tx-4',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-3',
    accountName: 'Billetera Yape',
    categoryName: 'Restaurantes',
    categoryIcon: 'Utensils',
    categoryColor: '#ec4899',
    amount: 78.0,
    currency: 'PEN',
    type: 'EXPENSE',
    description: 'Cena de viernes en pareja',
    transactionDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paidByUserName: 'Tú',
  },
  {
    id: 'demo-tx-5',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-1',
    accountName: 'BCP Sueldo',
    categoryName: 'Transporte',
    categoryIcon: 'Car',
    categoryColor: '#3b82f6',
    amount: 54.0,
    currency: 'PEN',
    type: 'EXPENSE',
    description: 'Combustible Primax',
    transactionDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    paidByUserName: 'Tú',
  },
];

export const DEMO_BUDGETS: BudgetDTO[] = [
  {
    id: 'demo-b-1',
    name: 'Supermercado & Alimentación',
    categoryName: 'Alimentación',
    limitAmount: 1400.0,
    spentAmount: 890.0,
    currency: 'PEN',
    workspaceId: DEMO_WORKSPACE_ID,
    status: 'ON_TRACK',
  },
  {
    id: 'demo-b-2',
    name: 'Servicios Básicos & Hogar',
    categoryName: 'Servicios',
    limitAmount: 450.0,
    spentAmount: 395.0,
    currency: 'PEN',
    workspaceId: DEMO_WORKSPACE_ID,
    status: 'WARNING',
  },
  {
    id: 'demo-b-3',
    name: 'Entretenimiento & Salidas',
    categoryName: 'Restaurantes',
    limitAmount: 600.0,
    spentAmount: 240.0,
    currency: 'PEN',
    workspaceId: DEMO_WORKSPACE_ID,
    status: 'ON_TRACK',
  },
];

export const DEMO_GOALS: SavingsGoalDTO[] = [
  {
    id: 'demo-goal-1',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-2',
    name: 'Fondo de Emergencia (6 meses)',
    targetAmount: 15000.0,
    currentAmount: 8200.0,
    currency: 'PEN',
    category: 'EMERGENCY',
    deadlineDate: '2026-12-31',
  },
  {
    id: 'demo-goal-2',
    workspaceId: DEMO_WORKSPACE_ID,
    accountId: 'demo-acc-2',
    name: 'Vacaciones Fin de Año',
    targetAmount: 4000.0,
    currentAmount: 2600.0,
    currency: 'PEN',
    category: 'TRAVEL',
    deadlineDate: '2026-11-30',
  },
];

export const DEMO_SUBSCRIPTIONS: SubscriptionDTO[] = [
  {
    id: 'demo-sub-1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Fibra Óptica 300 Mbps',
    amount: 119.0,
    currency: 'PEN',
    dueDay: 15,
    category: 'UTILITIES',
    isPaidThisMonth: true,
    provider: 'Claro Perú',
  },
  {
    id: 'demo-sub-2',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Netflix Premium Familiar',
    amount: 49.9,
    currency: 'PEN',
    dueDay: 22,
    category: 'SUBSCRIPTION',
    isPaidThisMonth: false,
    provider: 'Netflix',
  },
  {
    id: 'demo-sub-3',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Gimnasio SmartFit Plan Black',
    amount: 109.9,
    currency: 'PEN',
    dueDay: 28,
    category: 'HEALTH',
    isPaidThisMonth: false,
    provider: 'SmartFit',
  },
];

export const DEMO_INVESTMENTS: InvestmentDTO[] = [
  {
    id: 'demo-inv-1',
    name: 'Fondo Indexado S&P 500 (VOO)',
    type: 'STOCKS',
    institution: 'Hapi / Interactive Brokers',
    initialCapital: 3500.0,
    currentValue: 3980.0,
    returnsAmount: 480.0,
    returnsPercentage: 13.71,
    currency: 'USD',
    workspaceId: DEMO_WORKSPACE_ID,
  },
  {
    id: 'demo-inv-2',
    name: 'Depósito a Plazo Fijo 7.2% TEA',
    type: 'FIXED_TERM',
    institution: 'Caja Piura',
    initialCapital: 5000.0,
    currentValue: 5360.0,
    returnsAmount: 360.0,
    returnsPercentage: 7.2,
    currency: 'PEN',
    workspaceId: DEMO_WORKSPACE_ID,
  },
];

export const DEMO_SETTLEMENT_SUMMARY: DebtBalanceSummaryDTO = {
  workspaceId: DEMO_COUPLE_WORKSPACE_ID,
  totalSharedExpenses: 1840.0,
  partnerAEmail: 'demo@dualis.app',
  partnerAPaidTotal: 1200.0,
  partnerAShareTotal: 920.0,
  partnerBEmail: 'sofia@demo.app',
  partnerBPaidTotal: 640.0,
  partnerBShareTotal: 920.0,
  totalSettledAmount: 0.0,
  netBalance: 280.0,
  debtorEmail: 'sofia@demo.app',
  creditorEmail: 'demo@dualis.app',
  summaryText: 'Sofía te debe S/ 280.00 PEN para equilibrar los gastos compartidos del 50/50.',
};

export const DEMO_SALARY_CONFIG: SalaryDistributionConfig = {
  enabled: true,
  frequency: 'MONTHLY',
  paymentDay: 30,
  distributionType: 'SPLIT',
  autoExecute: true,
  branches: [
    {
      id: 'demo-branch-1',
      destinationType: 'ACCOUNT',
      targetAccountId: 'demo-acc-1',
      targetAccountName: 'BCP Sueldo / Principal',
      mode: 'PERCENTAGE',
      value: 50,
      label: 'Gastos Operativos del Mes',
    },
    {
      id: 'demo-branch-2',
      destinationType: 'ACCOUNT',
      targetAccountId: 'demo-acc-2',
      targetAccountName: 'Interbank Ahorro Emergencia',
      mode: 'PERCENTAGE',
      value: 30,
      label: 'Ahorro / Fondo de Tranquilidad',
    },
    {
      id: 'demo-branch-3',
      destinationType: 'INVESTMENT',
      targetInvestmentId: 'demo-inv-1',
      targetInvestmentName: 'Fondo Indexado S&P 500',
      mode: 'PERCENTAGE',
      value: 20,
      label: 'Inversión a Largo Plazo',
    },
  ],
};

export const DEMO_DASHBOARD_SUMMARY: DashboardSummaryDTO = {
  totalBalance: 12180.0,
  totalLiquidity: 13430.0,
  currency: 'PEN',
  monthlyIncome: 6500.0,
  monthlyExpenses: 2850.0,
  netSavings: 3650.0,
  savingsRatePercentage: 56.15,
  savingsRate: 56.15,
  essentialExpenses: 1850.0,
  nonEssentialExpenses: 1000.0,
  essentialPercentage: 64.9,
  nonEssentialPercentage: 35.1,
  activeBudgetsCount: 3,
  exceededBudgetsCount: 0,
};
